### PR TITLE
Fix NormalizeWhitespace not inserting spaces between expression list arguments.

### LINKED ISSUE #108: NormalizeWhitespace should insert/preserve spaces between call arguments.
NormalizeWhitespace does not insert/preserve spaces between function call arguments. Having spaces between arguments is considered "normal" and should be added.

```lua
print(1, 2)
```

After ``NormalizeWhitespace()`` is called on the tree, it will be formatted as the following:

```lua
print(1,2)
```

### PR DESCRIPTION
**Pull request by TheGreatSageEqualToHeaven**
Adds missing `VisitExpressionListFunctionArgument` method to the SyntaxNormalizer 

Fixes #108

### CODE REVIEW

File: src/Compilers/Lua/Portable/Syntax/SyntaxNormalizer.cs [hunk 1]
```diff
@@ -957,6 +957,19 @@ private void AddSpacesAroundToken(SyntaxToken token)
             return base.VisitMethodCallExpression(node);
         }
 
+        // function_argument
+        //  : expression_list_function_argument
+        //  | string_function_argument
+        //  | table_constructor_function_argument
+        //  ;
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Portable/Syntax/SyntaxNormalizer.cs:964]: This isn't the exact definition for the expression list function argument

File: src/Compilers/Lua/Test/Portable/Syntax/SyntaxNormalizerTests.cs [hunk 2]
```diff
@@ -1223,6 +1224,17 @@ public void SyntaxNormalizer_CorrectlyRewritesTypes(string input, string expecte
             AssertNormalizeCore(type, expected);
         }
 
+        [Fact]
+        [WorkItem(108, "https://github.com/LorettaDevs/Loretta/issues/108")]
+        public void SyntaxNormalizer_CorrectlyInsertsExpressionSpaces()
+        {
+            var tree = ParseAndValidate("print(1, 2)", s_luaParseOptions);
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Test/Portable/Syntax/SyntaxNormalizerTests.cs:1231]: It'd be better to add an input with messed up indentation here to ensure we're actually formatting the code and not just spitting out the code that gets input

**Review by GGG-KILLER — CHANGES_REQUESTED** [review]
Pretty good, only a few minor nits

**Review by GGG-KILLER — APPROVED** [review]
All good now, thanks!
