### PR TITLE
Temporarily disable the token cache

### LINKED ISSUE #152: Lexer token cache incorrectly caches tokens which have different values in different syntax options
### What is the issue you are experiencing?

Title

### What was the expected result?

The token cache either does not exist, or correctly handles all cases which are different in lexing due to syntax options.
Example:
```cs
        var str = @"
                     repeat
                         m, E = G:zR(E, H);
                         if m == 0x7423 then
                             break;
                         else
                             if m ~= 0X76D4 then
                             else
                                 continue;
                             end;
                         end;
                     until false;
        ";
        
        var syntaxTree = LuaSyntaxTree.ParseText(str, new LuaParseOptions(LuaSyntaxOptions.Lua51));
        var syntaxTree2 = LuaSyntaxTree.ParseText(str, new LuaParseOptions(LuaSyntaxOptions.Luau));
        
        if (syntaxTree.GetDiagnostics().Any() && syntaxTree2.GetDiagnostics().Any())
            Assert.Fail("Token cache incorrectly cached continue");
```

### What was the actual result?

The token cache incorrectly cached tokens

### What are the steps to reproduce this issue?

**DO NOT POST A LINK TO YOUR REPO, MAKE A SMALL REPRODUCTION SAMPLE**

...
N. See error

### What version of Loretta are you experiencing this issue in?

v0.2.14-nightly.5

### What Lua versions are affected by this issue?

_No response_

### Is there any additional information you wish to add?

_No response_

### Please ensure you have done the following actions:

- [x] I have checked that there are no similar issues already open.
- [x] I confirm this is not an usage question but an actual bug within Loretta.
- [x] I have confirmed that this issue still happens on the latest nightly version.
- [x] I have confirmed that this issue is because of Loretta and not because of my own code.
- [x] I acknowledge my issue will be closed if any step has been skipped.

### PR DESCRIPTION
**Pull request by toxamin**
Temporarily disable the token cache. Fixes #152.

### CODE REVIEW

File: src/Compilers/Lua/Portable/Parser/Lexer.QuickScanner.cs
Comment (GGG-KILLER) [inline src/Compilers/Lua/Portable/Parser/Lexer.QuickScanner.cs:1]: I'd prefer this not be removed entirely since I'd rather keep it.

There was nothing wrong with the Lexer specifically, but only with the function that checks whether a token can be reused.

File: src/Compilers/Lua/Portable/Parser/Lexer.cs [hunk 1]
```diff
@@ -65,7 +66,7 @@ public override void Dispose()
             base.Dispose();
         }
 
-        public SyntaxToken Lex() => QuickScanSyntaxToken() ?? LexSyntaxToken();
+        public SyntaxToken Lex() => LexSyntaxToken();
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Portable/Parser/Lexer.cs:69]: Instead of deleting, add `#if LEXER_TOKEN_CACHE` so that it can be easily re-enabled without having to revert this commit as this is a temporary hotfix.

File: src/Compilers/Lua/Portable/Parser/LexerCache.cs
Comment (GGG-KILLER) [inline src/Compilers/Lua/Portable/Parser/LexerCache.cs:1]: Don't delete anything from here, just make it not be used wherever it was being called as a temp fix.

File: src/Compilers/Lua/Portable/Syntax/SyntaxEquivalence.cs [hunk 2]
```diff
@@ -64,9 +70,12 @@ private static bool AreTokensEquivalent(GreenNode? before, GreenNode? after)
...
             return (SyntaxKind) before.RawKind switch
             {
-                SyntaxKind.IdentifierToken => ((Green.SyntaxToken) before).ValueText != ((Green.SyntaxToken) after).ValueText,
-                SyntaxKind.NumericLiteralToken
-                or SyntaxKind.StringLiteralToken => ((Green.SyntaxToken) before).Text != ((Green.SyntaxToken) after).Text,
+                SyntaxKind.IdentifierToken => ((Green.SyntaxToken) before).ValueText ==
+                                              ((Green.SyntaxToken) after).ValueText,
+                SyntaxKind.NumericLiteralToken or SyntaxKind.StringLiteralToken
+                    or SyntaxKind.InterpolatedStringTextToken or SyntaxKind.InterpolatedStringToken
+                    or SyntaxKind.HashStringLiteralToken or SyntaxKind.BadToken => ((Green.SyntaxToken) before).Value ==
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Portable/Syntax/SyntaxEquivalence.cs:77]: Why is `BadToken` added here?

File: src/Compilers/Lua/Test/Portable/Lexical/RegressionTests.cs [hunk 3]
```diff
@@ -143,4 +143,31 @@ await Assert.That(token).HasKind(SyntaxKind.StringLiteralToken).And.HasText(rawT
...
+                             end;
+                         end;
+                     until false;
+        ";
+        
+        var syntaxTree = LuaSyntaxTree.ParseText(str, new LuaParseOptions(LuaSyntaxOptions.Lua51));
+        var syntaxTree2 = LuaSyntaxTree.ParseText(str, new LuaParseOptions(LuaSyntaxOptions.Luau));
+        
+        if (syntaxTree.GetDiagnostics().Any() && syntaxTree2.GetDiagnostics().Any())
+            Assert.Fail("Token cache did not handle syntax options correctly");
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Test/Portable/Lexical/RegressionTests.cs:169]: Instead of checking if there are any diagnostics, check that they don't share the same diagnostics instead.

Preferably use `.Verify`.

File: src/Compilers/Lua/Test/Portable/Lexical/RegressionTests.cs [hunk 4]
```diff
@@ -143,4 +143,31 @@ await Assert.That(token).HasKind(SyntaxKind.StringLiteralToken).And.HasText(rawT
...
+        
+        return Task.CompletedTask;
```
Comment (GGG-KILLER) [inline src/Compilers/Lua/Test/Portable/Lexical/RegressionTests.cs:171]: No need for this line, just make the method `void`.

**Review by GGG-KILLER — CHANGES_REQUESTED** [review]
Thank you for your contribution, but the change as it is is too radical.

File: src/Compilers/Lua/Portable/Syntax/SyntaxEquivalence.cs [hunk 5]
```diff
@@ -64,9 +70,12 @@
...
+                                                            ((Green.SyntaxToken) after).Value,
```
[the remark this answers is not in the document]
Comment (GGG-KILLER) [reply src/Compilers/Lua/Portable/Syntax/SyntaxEquivalence.cs:78]: This is also an issue that needs to be fixed.

[the remark this answers is not in the document]
Comment (GGG-KILLER) [reply src/Compilers/Lua/Portable/Syntax/SyntaxEquivalence.cs:78]: This is also a big issue that needs to be fixed, this check will never pass the way it is currently.
